root: true
extends: 
  - airbnb-base
  - airbnb-typescript/base
parserOptions:
  project: './tsconfig.json'
  sourceType: module
  ecmaVersion: 13
rules:
  brace-style:
    - error
    - stroustrup
  react/react-in-jsx-scope:
    off